"""modernize models

Revision ID: 7a5a59efd8d4
Revises: 436fd12c4eb5
Create Date: 2026-05-02 23:31:55.645956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a5a59efd8d4'
down_revision: Union[str, Sequence[str], None] = '436fd12c4eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('notes', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('refresh_tokens', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('workspaces', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('workspaces', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('refresh_tokens', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('notes', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('notes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('notes', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
